// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Wediplan.Api.Data;

#nullable disable

namespace Wediplan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914140014_InitFaza1")]
    partial class InitFaza1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wediplan.Api.Domain.DailyStat", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<string>("CategorySlug")
                        .HasColumnType("text")
                        .HasColumnName("category_slug");

                    b.Property<string>("RegionSlug")
                        .HasColumnType("text")
                        .HasColumnName("region_slug");

                    b.Property<string>("VendorSlug")
                        .HasColumnType("text")
                        .HasColumnName("vendor_slug");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("Day", "EventName", "CategorySlug", "RegionSlug", "VendorSlug");

                    b.ToTable("daily_stats", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<string>("Page")
                        .HasColumnType("text")
                        .HasColumnName("page");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb")
                        .HasColumnName("props");

                    b.Property<string>("SessionHash")
                        .HasColumnType("text")
                        .HasColumnName("session_hash");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("Ts");

                    b.HasIndex("EventName", "Ts");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.ImportedReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("imported_reviews", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.Sponsorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("sponsorships", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_slug");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_status");

                    b.Property<bool>("CoverageAll")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_all");

                    b.Property<string>("CoverageNote")
                        .HasColumnType("text")
                        .HasColumnName("coverage_note");

                    b.Property<List<string>>("CoverageRegions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("coverage_regions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<bool>("LiveCalendar")
                        .HasColumnType("boolean")
                        .HasColumnName("live_calendar");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("LocationPrecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("OptOut")
                        .HasColumnType("boolean")
                        .HasColumnName("opt_out");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("PriceFrom")
                        .HasColumnType("integer")
                        .HasColumnName("price_from");

                    b.Property<string>("PriceKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_kind");

                    b.Property<int?>("PriceTo")
                        .HasColumnType("integer")
                        .HasColumnName("price_to");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("RatingSource")
                        .HasColumnType("text")
                        .HasColumnName("rating_source");

                    b.Property<string>("RegionSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_slug");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "City", "About" });

                    b.Property<List<string>>("Services")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("services");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SocialFacebook")
                        .HasColumnType("text")
                        .HasColumnName("social_facebook");

                    b.Property<string>("SocialInstagram")
                        .HasColumnType("text")
                        .HasColumnName("social_instagram");

                    b.Property<List<string>>("StyleTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("style_tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("CategorySlug");

                    b.HasIndex("City");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("City"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("City"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RegionSlug");

                    b.HasIndex("Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.VendorCategory", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("CategorySlug")
                        .HasColumnType("text")
                        .HasColumnName("category_slug");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("VendorId", "CategorySlug");

                    b.HasIndex("CategorySlug");

                    b.ToTable("vendor_categories", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.VendorPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("vendor_photos", (string)null);
                });

            modelBuilder.Entity("Wediplan.Api.Domain.ImportedReview", b =>
                {
                    b.HasOne("Wediplan.Api.Domain.Vendor", "Vendor")
                        .WithMany("ImportedReviews")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Wediplan.Api.Domain.VendorCategory", b =>
                {
                    b.HasOne("Wediplan.Api.Domain.Vendor", "Vendor")
                        .WithMany("Categories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Wediplan.Api.Domain.VendorPhoto", b =>
                {
                    b.HasOne("Wediplan.Api.Domain.Vendor", "Vendor")
                        .WithMany("Photos")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Wediplan.Api.Domain.Vendor", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ImportedReviews");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
